file:
  location: /tmp

server:
  port: 8443

 # ssl:
 #   key-store: classpath:keystore.p12
 #   key-store-type: PKCS12
 #   key-store-password: ENC(3XCwNNVyBH1PRmYmKVR0T1e57cn3SuDz)

spring:
  security:
    user:
      name: admin
      password: 1234
    oauth2:
      client:
        registration:
          google:
            client-id: 570359168440-4c9rb93ojhnjeqa0oeo68u5snn6eqems.apps.googleusercontent.com
            client-secret: ENC(DiBIF3zRy1synu9+qwAfWSBQo+xWdi5cEAvcbNNyrS1oFI0A2CSEFw==)
            scope: profile, email
          facebook:
            client-id: 623339641909955
            client-secret: ENC(8ItpeyX9DVTov6SVTDTATOkYo7CDaXmuCc3pXsMC//84nz0EpWRgnviiruQ3imIJ)
          naver:
            client-id: GmzOlRvlSvYxqdF5PP7a
            client-secret: ENC(NLJ8Ufq1QoosfYZbJMWkDEwMViWAljSc)
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver
          github:
            clientId: ab0174180f853666f31f
            clientSecret: ENC(++LIvWFvLDzU/R4UDd2bLWivCT7rAH49wiaqxR60lClLv8E8VmX/gf4+MSOLzP1BXhWBjHAQcoo=)
        provider:
          facebook:
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture,link
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  redis:
    host: 141.164.53.200
    port: 6379
    password: 123qwe!@#$
    lettuce:
      pool:
        max-active: 30  # 최대 가용 connection 갯수
        max-idle: 10 # pool에 미리 가지고 있을 connection 최대 갯수
        min-idle: 2 # pool에 미리 가지고 있을 connection 최소 갯수

  redis2:
    host: 141.164.53.200
    port: 7000
    password: 123qwe!@#$
    lettuce:
      pool:
        max-active: 30  # 최대 가용 connection 갯수
        max-idle: 10 # pool에 미리 가지고 있을 connection 최대 갯수
        min-idle: 2 # pool에 미리 가지고 있을 connection 최소 갯수

  freemarker:
    check-template-location: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: kimcoding9418@gmail.com
    password: ENC(3XCwNNVyBH1PRmYmKVR0T1e57cn3SuDz)
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
        mime:
          charset: UTF-8
          transport:
            protocol: smtp
    default-encoding: UTF-8

  datasource:
    url: jdbc:h2:mem:portaldb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    #url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2

  # enable H2 web console and set url for web console
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    generate-ddl: false

    properties:
      hibernate:
        show_sql: true # SQL 표시
        format_sql: true # SQL 포맷팅
        use_sql_comments: true # 주석 표시

    # springboot-jpa LazyInitializationException
  profile:
    value: local
#    properties:
#      hibernate:
#        enable_lazy_load_no_trans: true

logging:
  level:
    root: warn
    com.simple.portal: debug
    org:
      hibernate:
        type:
          descriptor:
            sql: trace # 값 매핑

# s3 설정
cloud:
  aws:
    credentials:
      accessKey: ENC(FGBw07GDjTI8V17aSK6sf+8y1nKxpzgNYlUOR7mNPjA=)
      secretKey: ENC(c15fPgJ3CShuIlX4VdCElP3iLcGj6ihoV48VjmhbpE0Uyc2mZeeIwzmDzYkhz7HN15K5rZuY2Ew=)
    s3:
      bucket: portal-file
    region:
      static: whatever
    stack:
      auto: false

# jwt token key 설정
jwt:
  token:
    key: ENC(CmTLZAzvVCxXUeBquPXymOzjdEZ9vEOi)